### PR TITLE
feat!: merge next-major into master

### PR DESCRIPTION
**Pull request by GreenRover**
Description

This PR merges `next-major` branch into `master`.

Warning
DO NOT SQUASH. USE REBASE OR MERGE

`next-major` branch includes the rewrite to TypeScript and adapts to the new Parser-API interface.
It is BC (see commits included with `feat!:` prefix).

Related issue(s)
https://github.com/asyncapi/parser-js/issues/481

### CODE REVIEW

**Comment by GreenRover** [comment]
@derberg  or @fmvilas can you please review build and publishing. I am not sure if i get all essential parts of application.json

**Comment by derberg** [comment]
actually the best for review would be @smoya 

also, @smoya can you please have a look at https://github.com/asyncapi/protobuf-schema-parser/pull/20

please add this protobuf template to https://github.com/asyncapi/parser-js/blob/master/.github/workflows/bump.yml#L35 once this PR is merged. So only RC updates will come from bot from JS Parser. Now bot will bomb this project with automated bumps from any release, main or RC

**Comment by smoya** [comment]
> also, @smoya can you please have a look at #20

Added a comment about why that PR is failing.

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Comment by derberg** [comment]
@GreenRover before you get approval from @nathanaelweber and merge, remember about adjusting PR title prefix to `feat!: ` as you need to release this one as 2.0

**Comment by smoya** [comment]
> @GreenRover before you get approval from @nathanaelweber and merge, remember about adjusting PR title prefix to `feat!: ` as you need to release this one as 2.0

Too late, but two things to say here:

1. That was totally not needed if the merge is done without the `/rtm` as @GreenRover suggested. In this case, not really needed since there was only one commit and the author is still @GreenRover.
2. The commit message now it's not correct: `[feat!: merge next-major into master](https://github.com/asyncapi/protobuf-schema-parser/pull/15#top)` VS `feat!: implement new Parser-js interface`. but now is merged, and released with that title as breaking change 😅

**Comment by derberg** [comment]
actually I do not see 2.0 was released

**Pull request merged**
